package theme.color

import androidx.compose.ui.graphics.Color

// light colors
val primaryLight = Color(0xFFFECA30)
val onPrimaryLight = Color(0xFF1F1B13)
val primaryContainerLight = Color(0xFFFFDF94)
val onPrimaryContainerLight = Color(0xFF1F1B13)
val secondaryLight = Color(0xFF126682)
val onSecondaryLight = Color(0xFF1B361E)
val secondaryContainerLight = Color(0xFFFCFEFF)
val onSecondaryContainerLight = Color(0xFF001F2A)
val tertiaryLight = Color(0xFFFFF8F1)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFCAEBC7)
val onTertiaryContainerLight = Color(0xFF05210A)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFBA1A1A)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFFFFFFF)
val onBackgroundLight = Color(0xFF1F1B13)
val surfaceLight = Color(0xFFFFF8F1)
val onSurfaceLight = Color(0xFF1F1B13)
val surfaceVariantLight = Color(0xFFECE1CF)
val onSurfaceVariantLight = Color(0xFF4C4639)
val outlineLight = Color(0xFF7E7667)
val outlineVariantLight = Color(0xFFCFC5B4)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF343027)
val inverseOnSurfaceLight = Color(0xFFF9F0E2)
val inversePrimaryLight = Color(0xFFE5C36C)
val surfaceDimLight = Color(0xFFE2D9CC)
val surfaceBrightLight = Color(0xFFFFF8F1)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFFCF2E5)
val surfaceContainerLight = Color(0xFFF6EDDF)
val surfaceContainerHighLight = Color(0xFFF0E7D9)
val surfaceContainerHighestLight = Color(0xFFEAE1D4)

// dark colors
val primaryDark = Color(0xFFFEEEBF)
val onPrimaryDark = Color(0xFF3E2E00)
val primaryContainerDark = Color(0xFF2A2000)
val onPrimaryContainerDark = Color(0xFFFFDF94)
val secondaryDark = Color(0xFF8BD0EF)
val onSecondaryDark = Color(0xFFCAEBC7)
val secondaryContainerDark = Color(0xFF001F2A)
val onSecondaryContainerDark = Color(0xFFFCFEFF)
val tertiaryDark = Color(0xFFFEEEBF)
val onTertiaryDark = Color(0xFF1B361E)
val tertiaryContainerDark = Color(0xFF314D33)
val onTertiaryContainerDark = Color(0xFFCAEBC7)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF16130B)
val onBackgroundDark = Color(0xFFEAE1D4)
val surfaceDark = Color(0xFF16130B)
val onSurfaceDark = Color(0xFFEAE1D4)
val surfaceVariantDark = Color(0xFF4C4639)
val onSurfaceVariantDark = Color(0xFFCFC5B4)
val outlineDark = Color(0xFF989080)
val outlineVariantDark = Color(0xFF4C4639)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFEAE1D4)
val inverseOnSurfaceDark = Color(0xFF343027)
val inversePrimaryDark = Color(0xFF755B0B)
val surfaceDimDark = Color(0xFF16130B)
val surfaceBrightDark = Color(0xFF3D392F)
val surfaceContainerLowestDark = Color(0xFF001F2A)
val surfaceContainerLowDark = Color(0xFF1F1B13)
val surfaceContainerDark = Color(0xFF231F17)
val surfaceContainerHighDark = Color(0xFF2E2921)
val surfaceContainerHighestDark = Color(0xFF39342B)

